cookie:
  expiry_days: 1
  key: random_signature_key
  name: pfad_auth
credentials:
  usernames:
    admin:
      email: admin@pfad.local
      name: Admin User
      password: $2b$12$bjQKYzS3zXcUcgXjvoJFZeStu.xfWJrAikUNYBXdYYDVy28iZIrFa
